### PR TITLE
Update Nextcloud 24 & php-cs-fixer cleaning

### PR DESCRIPTION
**Pull request by bonswouar**
@marcelklehr I hope you don't mind I also ran `php-cs-fixer` for a cleaner php code

### CODE REVIEW

**Comment by marcelklehr** [comment]
> I hope you don't mind I also ran php-cs-fixer for a cleaner php code

Did you run `composer run cs:fix`? That one uses the official Nextcloud coding style ;)

**Comment by marcelklehr** [comment]
We should also add an entry for NC24 to the CI matrix

**Comment by bonswouar** [comment]
> Did you run composer run cs:fix? That one uses the official Nextcloud coding style ;)

I didn't know about that one :sweat_smile:
Done!

> We should also add an entry for NC24 to the CI matrix

Done, although I haven't checked much how those Matrix params work, let me know if I forgot anything :)

**Review by marcelklehr — APPROVED** [review]

**Comment by marcelklehr** [comment]
Ah, damn it. I forgot that NC24 drops support for php7.3 we need to remove that from the matrix

**Comment by bonswouar** [comment]
> Ah, damn it. I forgot that NC24 drops support for php7.3 we need to remove that from the matrix

Oh right! I didn't find the condensed changelog for NC 24, could have been useful

**Comment by marcelklehr** [comment]
I've cleaned up the matrix a bit and dropped support for NC20 and NC21, which are eol anyway according to https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Pull request merged**
